spring:
  application:
    name: auth-service
server:
  port: 8082
---
spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/db_account_banking
    username: postgres
    password: 1111
  logging:
    level:
      io.r2dbc.postgresql.QUERY: DEBUG  # Shows actual SQL
      org.springframework.data.r2dbc: DEBUG
      io.r2dbc: DEBUG
  data:
    redis:
      host: localhost
      port: 6379
---
management:
  endpoints:
    web:
      exposure:
        include: health,info,beans,loggers
  endpoint:
    health:
      show-details: always

---
spring:
    banner:
      location: file:./banner.txt
logging:
  config: classpath:log4j2-spring.xml
---
jwt:
  secretKey: 16502ee43b73ce88149ca42ab31db111063820asdbd106505a6sfsafg345ecbb33a7bbe6b38578b23baee473c7aaf89c8e490c8e1429fbb264f137d1e2b3fb2ef396d8
  accessTokenExpirationTime: 259200000 # 3 days
  refreshTokenExpirationTime: 2419200000 # 2 weeks
  resetPasswordTokenExpirationTime: 900000 # 15 minutes
---