spring:
  application:
    name: auth-service
server:
  port: 8082
---
spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/db_account_banking
    username: postgres
    password: 1111
  logging:
    level:
      io.r2dbc.postgresql.QUERY: DEBUG  # Shows actual SQL
      org.springframework.data.r2dbc: DEBUG
      io.r2dbc: DEBUG
  data:
    redis:
      host: localhost
      port: 6379
  rabbitmq:
    port: 5672
    host: localhost
    username: guest
    password: guest
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 5
          initial-interval: 1000ms
          multiplier: 2.0
          max-interval: 10000ms
---
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
---
management:
  endpoints:
    web:
      exposure:
        include: health,info,beans,loggers
  endpoint:
    health:
      show-details: always

---
spring:
    banner:
      location: file:./banner.txt
logging:
  config: classpath:log4j2-spring.xml
---
jwt:
  secretKey: 16502ee43b73ce88149ca42ab31db111063820asdbd106505a6sfsafg345ecbb33a7bbe6b38578b23baee473c7aaf89c8e490c8e1429fbb264f137d1e2b3fb2ef396d8
  accessTokenExpirationTime: 259200000 # 3 days
  refreshTokenExpirationTime: 2419200000 # 2 weeks
  resetPasswordTokenExpirationTime: 900000 # 15 minutes
---
rabbitmq:
  exchangeName: banking-demo
  user-mail-routing-key: banking-demo
  user-mail-queue: banking-otp-queue
---
management:
  tracing:
    sampling:
      probability: 1.0   # 1.0 = ghi trace 100%, thường để 0.1 (10%) cho production
  otlp:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans   # endpoint Zipkin

---
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: hduy09092005@gmail.com
    password: srwmlebtfrsfdxkl
    protocol: smtp
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: false
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

