spring:
  application:
    name: api-gateway
server:
  port: 8083
---
spring:
    banner:
      location: file:./banner.txt
logging:
  config: classpath:log4j2-spring.xml
---
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
---
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    disable-swagger-default-url: true
    urls:
      - name: auth-service
        url: /auth-service/v3/api-docs

      - name: user-service
        url: /user-service/v3/api-docs

      - name: transaction-service
        url: /transaction-service/v3/api-docs

      - name: wallet-service
        url: /wallet-service/v3/api-docs

---
spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: http://localhost:8080
              predicates:
                - Path=/user-service/**
              filters:
               - StripPrefix=1

            - id: transaction-service
              uri: http://localhost:8081
              predicates:
                - Path=/transaction-service/**
              filters:
                - StripPrefix=1

            - id: wallet-service
              uri: http://localhost:8084
              predicates:
                - Path=/wallet-service/**
              filters:
                - StripPrefix=1

            - id: auth-service
              uri: http://localhost:8082
              predicates:
                - Path=/auth-service/**
              filters:
                - StripPrefix=1