spring:
  application:
    name: wallet-service
server:
  port: 8084
---
spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/db_wallet_banking
    username: postgres
    password: 1111
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
---
spring:
    banner:
      location: file:./banner.txt

logging:
  config: classpath:log4j2-spring.xml