spring:
  application:
    name: user-service
server:
  port: 8180
---
spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/db_user_banking
    username: postgres
    password: 1111
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
---
spring:
    banner:
      location: file:./banner.txt
logging:
  config: classpath:log4j2-spring.xml
---
grpc:
  client:
    hello:
      address: 'static://localhost:9090'
      negotiationType: plaintext