package com.banking_app.user_service.infastructure.service;

import com.banking_app.user_service.application.service.IdentifyDocumentInformationService;
import com.banking_app.user_service.domain.repository.IdentifyDocumentInformationRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;

@Service
@RequiredArgsConstructor
public class IdentifyDocumentInformationServiceImpl implements IdentifyDocumentInformationService {
  private final IdentifyDocumentInformationRepository identifyDocumentInformationRepository;
}
