package com.banking_app.transaction_service.infastructure.service;

import com.banking_app.transaction_service.application.service.TransactionMethodDetailService;
import com.banking_app.transaction_service.domain.repository.TransactionMethodDetailRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;

@Service
@RequiredArgsConstructor
public class TransactionMethodDetailServiceImpl implements TransactionMethodDetailService {
  private final TransactionMethodDetailRepository transactionMethodDetailRepository;
}
